package fr.thomasfar.jaf.entities;

import fr.thomasfar.jaf.annotations.Entity;
import fr.thomasfar.jaf.annotations.entities.Json;
import fr.thomasfar.jaf.annotations.entities.NotMapped;

import java.util.UUID;

@Entity

public class DefaultEntity extends IEntity<UUID> {

    // automatically json serialized as "name"
    // automatically json deserialized from "name"
    // Getter and setter are automatically generated by the @Entity annotation
    private String name;

    // automatically json serialized as "default_description"
    // automatically json deserialized from "default_description"
    private String defaultDescription;

    @Json("test") private String tesT; // serialized as "test" because of the @Json annotation

    @NotMapped private String notMapped; // not serialized because of the @NotMapped annotation

    public DefaultEntity(String name) {
        super(UUID.randomUUID());
        this.name = name;
    }
}
