package fr.thomasfar.jaf.entities;

import fr.thomasfar.jaf.annotations.entities.AutoGenerated;
import fr.thomasfar.jaf.annotations.entities.Id;

import java.util.Date;

public class IEntity<T> {

    @Id
    protected final T id;

    @AutoGenerated
    protected final Date createdAt = new Date();

    @AutoGenerated
    protected Date updatedAt = new Date();

    public IEntity(T id) {
        this.id = id;
    }

    public String toJson() {
        return "{}";
    }
}
